[project]
name = "portfolio"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "flask>=3.0.3",
    "flask-mail>=0.10.0",
    "flask-wtf>=1.2.1",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "flake8>=7.3.0",
]
